const Text = {
    MorningMessage: "Good morning",
    AfternoonMessage: "Good afternoon",
    NightMessage: "Good evening",
    FooterMessage: "Made with 🍰",
    CustomiseMessage: "Customise Dashboard",
    CustomiseModalMessage: "Customise your dashboard",
    CatFactHeading: "Cat Fact 🐱",
    FoxImageHeading: "Fox 🦊",
    ProgrammingQuoteHeading: "Programming Quote 🐱‍💻",
    YearFactHeading: "Year Fact 🔢",
    AdviceHeading: "Advice 📝",
    DadJokeHeading: "Dad Joke 🤷‍♂️",
    YesOrNoHeading: "Yes or no ❔",
    LyricsHeading: "Search for lyrics 🎶",
    LyricsFormInputArtist: "Artist",
    LyricsFormInputSong: "Song",
    LyricsFormButton: "Search",
    LyricsModalHeading: "Search result",
    MusicPlayerHeading: "Play music ⏯️",
    RockMusicGenre: "Rock",
    LofiMusicGenre: "Lofi",
    PunkMusicGenre: "Punk",
    PokemonHeading: "Random pokemon ✨",
    PokemonNameHeading: "Name",
    PokemonNumHeading: "#",
    RPSHeading: "Play 🤘 🧻 ✂️",
    RPSPlayMessage: "Play Rock, Paper, Scissors",
    RPSOptionsMessage: "Select an option below!",
    RPSWinMessage: "You won!",
    RPSLoseMessage: "You lost...",
    RPSTieMessage: "It was a tie.",
    RPSPlayAgainMessage: "Play again",
}   

export default Text;